package fr.github.ethanpod.core.thread;

public enum EventType {
    NAVIGATION_UPDATED,
    INBOX_TOP8_UPDATED,
    INBOX_COUNT_UPDATED,
    QUEUE_TOP8_UPDATED,
    PODCAST_TOP8_UPDATED,
    DOWNLOAD_TOP8_UPDATED,
    PODCAST_BY_ID_UPDATED,
    EPISODE_BY_PODCAST_ID_UPDATED
}
