jdbc.database=jdbc:sqlite:
# Paramètres pour optimiser les performances et le rendu de JavaFX
# -------------------------------------------------------------
# Désactive les pulsations de l'animation pour réduire la charge CPU
javafx.animation.pulse=false
# Force l'exécution en un seul thread pour l'intégration (embedding)
javafx.embed.singleThread=true
# Définit l'ordre des pipelines de rendu, en priorisant le logiciel (software)
prism.order=sw
# Spécifie le moteur de rendu de texte à utiliser
prism.text=t2k
# Désactive le lissage de sous-pixel pour le texte
prism.subpixeltext=false
# Désactive le lissage de texte LCD pour le rendu
prism.lcdtext=false
# Paramètres de base de la connexion
# ---------------------------------
driverClassName=org.sqlite.JDBC
# Paramètres du pool de connexions HikariCP
# ----------------------------------------
maximumPoolSize=5
minimumIdle=1
connectionTimeout=5000
idleTimeout=300000
maxLifetime=1800000
keepaliveTime=120000
poolName=SQLitePool
# Propriétés de performance pour SQLite
# -------------------------------------
dataSource.journal_mode=WAL
dataSource.synchronous=NORMAL
dataSource.cache_size=10000
dataSource.foreign_keys=true
dataSource.busy_timeout=5000
dataSource.temp_store=MEMORY